include:
  - docker-compose.yml

services:
  ### DATABASE
  database:
    volumes:
      - "./config/database/backups/:/backup:rw"
      - "./config/database/dev-version/:/docker-entrypoint-initdb.d:ro"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  dbadmin:
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"

  ### BACK
  calculator:
    volumes:
      - "./Python/apps/backend_user/:/apps/backend_user/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_user.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
  auth:
    volumes:
      - "./Python/apps/backend_auth/:/apps/backend_auth/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_auth.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8081"
      - "--reload"
  backadmin:
    volumes:
      - "./Python/apps/backend_admin/:/apps/backend_admin/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_admin.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8082"
      - "--reload"

  ### FRONT
  frontend:
    build:
      target: "frontend"
    environment:
      - PORT=${ADMIN_FRONT_PORT}
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "node"
    volumes:
      - "./Node/apps/user-frontend/public:/app/public:ro"
      - "./Node/apps/user-frontend/src:/app/src:ro"
      - "./Node/apps/user-frontend/index.html:/app/index.html:ro"
      - "./Node/apps/user-frontend/tsconfig.json:/app/tsconfig.json:ro"
      - "./Node/apps/user-frontend/tsconfig.app.json:/app/tsconfig.app.json:ro"
      - "./Node/apps/user-frontend/tsconfig.node.json:/app/tsconfig.node.json:ro"
      - "./Node/apps/user-frontend/eslint.config.ts:/app/eslint.config.ts:ro"
      - "./Node/apps/user-frontend/vite.config.ts:/app/vite.config.ts:ro"
      - "./Node/apps/user-frontend/env.d.ts:/app/end.d.ts:ro"
      - "./Node/apps/user-frontend/package.json:/app/package.json:ro"
      - "./Node/apps/user-frontend/package-lock.json:/app/package-lock.json:ro"
    expose:
      - ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      reverseproxy:
    command: ["run", "dev"]

  adminfront:
    build:
      target: "frontadmin"
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
      - PORT=${ADMIN_FRONT_PORT}
      - VITE_PUBLIC_URL=/admin
      - REACT_ROUTING_MAIN_SITE=/
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: "node"
    volumes:
      - "./Node/apps/admin-frontend/public:/app/public:ro"
      - "./Node/apps/admin-frontend/src:/app/src:ro"
      - "./Node/apps/admin-frontend/index.html:/app/index.html:ro"
      - "./Node/apps/admin-frontend/tsconfig.json:/app/tsconfig.json:ro"
      - "./Node/apps/admin-frontend/eslint.config.mjs:/app/eslint.config.mjs:ro"
      - "./Node/apps/admin-frontend/vite.config.js:/app/vite.config.js:ro"
      - "./Node/apps/admin-frontend/package.json:/app/package.json:ro"
      - "./Node/apps/admin-frontend/package-lock.json:/app/package-lock.json:ro"
    expose:
      - ${ADMIN_FRONT_PORT}
    ports:
      - "${ADMIN_FRONT_PORT}:${ADMIN_FRONT_PORT}"
    networks:
      reverseproxy:
    command: ["start"]

  ### PROXY
  reverseproxy:
    depends_on:
      calculator:
        condition: service_started
      auth:
        condition: service_started
      backadmin:
        condition: service_started
      frontend:
        condition: service_started
      adminfront:
        condition: service_started
    volumes:
      - "./config/nginx/conf/nginx-dev.conf.template:/etc/nginx/templates/default.conf.template:ro"
      - "./config/nginx/conf/mime.types:/etc/nginx/conf.d/mime.types:ro"
      - "./Node/apps/old-user-frontend/:/www/old-frontend/:ro"
