services:
  ### DATABASE
  database:
    extends:
      service: database
      file: docker-compose.yml
    volumes:
      - "./config/database/backups/:/backup:rw"
      - "./config/database/dev-version/:/docker-entrypoint-initdb.d:ro"
    ports:
      - "${DB_PORT}:${DB_PORT}"
  dbadmin:
    extends:
      service: dbadmin
      file: docker-compose.yml
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      PMA_USER: "${DB_USER}"
      PMA_PASSWORD: "${DB_PASS}"

  ### BACK
  calculator:
    extends:
      service: calculator
      file: docker-compose.yml
    volumes:
      - "./Python/apps/backend_user/:/apps/backend_user/:ro"
      - "./Python/apps/module_data_fesco_api_adapter/:/apps/module_data_fesco_api_adapter/:ro"
      - "./Python/apps/module_data_internal/:/apps/module_data_internal/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_user.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
  auth:
    extends:
      service: auth
      file: docker-compose.yml
    volumes:
      - "./Python/apps/backend_auth/:/apps/backend_auth/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_auth.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8081"
      - "--reload"
  backadmin:
    extends:
      service: backadmin
      file: docker-compose.yml
    volumes:
      - "./Python/apps/backend_admin/:/apps/backend_admin/:ro"
      - "./Python/apps/module_data_fesco_api_adapter/:/apps/module_data_fesco_api_adapter/:ro"
      - "./Python/apps/module_data_internal/:/apps/module_data_internal/:ro"
      - "./Python/apps/module_shared/:/apps/module_shared/:ro"
      - "./resources/:/apps/resources/:rw"
    command:
      - "backend_admin.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8082"
      - "--reload"

  ### PROXY
  reverseproxy:
    extends:
      service: reverseproxy
      file: docker-compose.yml
    depends_on:
      calculator:
        condition: service_started
      auth:
        condition: service_started
      backadmin:
        condition: service_started
    volumes:
      - "./config/nginx/conf/nginx-dev-backend.conf.template:/etc/nginx/templates/default.conf.template:ro"
      - "./config/nginx/conf/mime.types:/etc/nginx/conf.d/mime.types:ro"
      - "./Node/apps/old-user-frontend/:/www/old-frontend/:ro"

networks:
  reverseproxy:
  db:
