services:
  calculator:
    build:
      dockerfile: "Dockerfile"
      target: "calculator"
    env_file:
      - ".env"
    volumes:
      - "./apps/backend/:/app/backend/:r"
    expose:
      - 8080
    networks:
      local:
    command:
      - "backend.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--reload"
  auth:
    build:
      dockerfile: "Dockerfile"
      target: "calculator"
    env_file:
      - ".env"
    volumes:
       - "./apps/auth/:/app/auth/:r"
    expose:
      - 8081
    networks:
      local:
    command:
      - "auth.main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8081"
      - "--reload"
  database:
    build:
      dockerfile: "Dockerfile"
      target: "database"
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_PASS}"
      MARIADB_DATABASE: "${DB_NAME}"
    volumes:
      - "./config/database/backups/:/backup:rw"
      - "./config/database/dev-version/:/docker-entrypoint-initdb.d:ro"
    expose:
      - 3306
    networks:
      local:
    entrypoint: ["docker-entrypoint.sh", "mariadbd"]
    healthcheck:
      test: >
        sh -c '
        mariadb-dump -u$${MARIADB_USER} -p$${MARIADB_PASSWORD} $${MARIADB_DATABASE} > /backup/last_dump.sql 2>/backup/dump_error.log;
        if [ $$? -eq 0 ]; then
        gzip /backup/last_dump.sql -c > /backup/$$(date -I)-dump.gz;
        rm /backup/last_dump.sql;
        exit 0;
        else
        exit 1;
        fi
        '
      interval: 30m
      retries: 3
  dbadmin:
    build:
      dockerfile: "Dockerfile"
      target: "dbadmin"
    expose:
      - 8080
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      local:
  reverseproxy:
    build:
      dockerfile: "Dockerfile"
      target: "reverseproxy"
    volumes:
      - "./config/nginx/conf/:/etc/nginx/:ro"
      - "./apps/frontend/:/www/frontend/:ro"
    networks:
      local:
    ports:
      - "${APP_PORT}:80"

networks:
  local:
