services:
  ### REDIS
  redis:
    image: valkey/valkey:alpine
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 999:999
    expose:
      - 6379
    command:
      - "redis-server"
      - "--maxmemory"
      - "128mb"
      - "--maxmemory-policy"
      - "volatile-lru"
    profiles:
      - test

  ### TEST
  test-runner:
    build:
      context: "./Python/"
      target: "test-runner"
    env_file:
      - ".env"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: 1000:1000
    volumes:
      - "./Python/apps/:/app/apps/:ro"
      - "./Python/tests/:/app/tests/:ro"
    profiles:
      - test
