"""v1.1-add-container-owner

Revision ID: 8180d7e4964c
Revises: dd480aa43c0c
Create Date: 2026-04-01 00:22:36.965300

"""
from email.policy import default
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8180d7e4964c'
down_revision: Union[str, Sequence[str], None] = 'dd480aa43c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices') as batch_op:
        batch_op.add_column(sa.Column('container_owner', sa.Enum('COC', 'SOC', name='containerowner', create_constraint=True), nullable=False, default='COC'))
        batch_op.alter_column('container_owner', server_default=None)
        batch_op.create_unique_constraint('route_id_1', ['route_id', 'container_owner', 'container_id', 'type'])
        batch_op.drop_index('route_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices') as batch_op:
        batch_op.create_unique_constraint('route_id', ['route_id', 'container_id', 'type'])
        batch_op.drop_index(op.f('route_id_1'), if_exists=True)
        batch_op.drop_column('container_owner')
    # ### end Alembic commands ###
