"""v1.0-init

Revision ID: dd480aa43c0c
Revises: 
Create Date: 2026-03-23 11:05:19.250245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd480aa43c0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4'
    )
    op.create_table('containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('weight_from', sa.Float(), nullable=False),
    sa.Column('weight_to', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('DC', 'HC', name='containertype', create_constraint=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size', 'type', 'weight_from', 'weight_to', 'name')
    )
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('RU_city', sa.String(length=100), nullable=True),
    sa.Column('RU_country', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'country')
    )
    op.create_table('drop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('sea_start_point_id', sa.Integer(), nullable=True),
    sa.Column('sea_end_point_id', sa.Integer(), nullable=True),
    sa.Column('rail_start_point_id', sa.Integer(), nullable=True),
    sa.Column('rail_end_point_id', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('conversation_percents', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=25), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['rail_end_point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['rail_start_point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['sea_end_point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['sea_start_point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sea_start_point_id', 'sea_end_point_id', 'rail_start_point_id', 'rail_end_point_id', 'container_id', 'company_id', 'effective_from', 'effective_to')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('start_point_id', sa.Integer(), nullable=False),
    sa.Column('end_point_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('SEA', 'RAIL', 'SEA_RAIL', name='routetypeenum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['end_point_id'], ['points.id'], ),
    sa.ForeignKeyConstraint(['start_point_id'], ['points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'start_point_id', 'end_point_id', 'effective_from', 'effective_to')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('conversation_percents', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('FIFOR', 'FILO', 'FOBFOR', 'MIXED', name='pricetypeenum', create_constraint=True), nullable=False),
    sa.ForeignKeyConstraint(['container_id'], ['containers.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'container_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices')
    op.drop_table('routes')
    op.drop_table('drop')
    op.drop_table('points')
    op.drop_table('containers')
    op.drop_table('companies')
    # ### end Alembic commands ###
