"""v1.2-correct-indexes-names

Revision ID: 2cfce045e792
Revises: 8180d7e4964c
Create Date: 2026-04-01 12:03:08.334740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cfce045e792'
down_revision: Union[str, Sequence[str], None] = '8180d7e4964c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uk__fingerprint', 'containers', ['size', 'type', 'weight_from', 'weight_to', 'name'])
    op.drop_index(op.f('size'), table_name='containers')
    op.create_unique_constraint('uk__fingerprint', 'drop', ['sea_start_point_id', 'sea_end_point_id', 'rail_start_point_id', 'rail_end_point_id', 'container_id', 'company_id', 'effective_from', 'effective_to'])
    op.drop_index(op.f('sea_start_point_id'), table_name='drop')
    op.create_unique_constraint('uk__location', 'points', ['city', 'country'])
    op.drop_index(op.f('city'), table_name='points')
    op.create_unique_constraint('uk__fingerprint', 'prices', ['route_id', 'container_id', 'type', 'container_owner'])
    op.drop_index(op.f('route_id_1'), table_name='prices')
    op.create_unique_constraint('uk__fingerprint', 'routes', ['company_id', 'start_point_id', 'end_point_id', 'effective_from', 'effective_to'])
    op.drop_index(op.f('company_id'), table_name='routes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('company_id'), 'routes', ['company_id', 'start_point_id', 'end_point_id', 'effective_from', 'effective_to'], unique=True)
    op.drop_constraint('uk__fingerprint', 'routes', type_='unique')
    op.create_index(op.f('route_id_1'), 'prices', ['route_id', 'container_owner', 'container_id', 'type'], unique=True)
    op.drop_constraint('uk__fingerprint', 'prices', type_='unique')
    op.create_index(op.f('city'), 'points', ['city', 'country'], unique=True)
    op.drop_constraint('uk__location', 'points', type_='unique')
    op.create_index(op.f('sea_start_point_id'), 'drop', ['sea_start_point_id', 'sea_end_point_id', 'rail_start_point_id', 'rail_end_point_id', 'container_id', 'company_id', 'effective_from', 'effective_to'], unique=True)
    op.drop_constraint('uk__fingerprint', 'drop', type_='unique')
    op.create_index(op.f('size'), 'containers', ['size', 'type', 'weight_from', 'weight_to', 'name'], unique=True)
    op.drop_constraint('uk__fingerprint', 'containers', type_='unique')
    # ### end Alembic commands ###
