"""v1.4-price-route-constraint-delete-cascade

Revision ID: 638ad167c6bd
Revises: 569fbebd37d5
Create Date: 2026-04-01 23:10:19.125749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638ad167c6bd'
down_revision: Union[str, Sequence[str], None] = '569fbebd37d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('2'), 'prices', type_='foreignkey')
    op.create_foreign_key('fk__price_route', 'prices', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk__price_route', 'prices', type_='foreignkey')
    op.create_foreign_key(op.f('2'), 'prices', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###
